### ISSUE TITLE
Password is in clear text in the log file

### ISSUE THREAD

**Issue by ukdtom** [vanstinator/UASViewer.bundle#6] opened 2016-02-11 22:41 UTC
When entering the prefs, password is in the log file in clear text!
Kanda a good idea to scramble that, IMHO

**Comment by vanstinator** [comment] 2016-02-11 23:03
That's a bug from an old debug statement. I'll remove it

**Comment by vanstinator** [comment] 2016-02-12 00:11
Digging through the code, not seeing this. Also not seeing it in my log. To clarify, we're talking about the uasviewer.log file correct?

**Comment by vanstinator** [comment] 2016-02-12 00:13
Ran my own password through my instance of Splunk and didn't come up with anything.

**Comment by ukdtom** [comment] 2016-02-12 00:32
I see this in the viewer log:

2016-02-12 01:27:28,630 (-b53a470) :  DEBUG (runtime:717) - Handling request GET /applications/UASViewer/:/prefs/set?PLEX_USERNAME=dane223&PLEX_PASSWORD=XXXX

And might be caused be the request module you are using?

**Comment by vanstinator** [comment] 2016-02-12 01:17
Closing as I cannot reproduce this on the latest version of the codebase. Feel free to reopen if you think this is still a problem.

**Comment by vanstinator** [comment] 2016-02-12 01:58
Your last comment just came through. I'm re-examining this.

**Comment by vanstinator** [comment] 2016-02-12 14:00
Reading the API docs and not seeing any way of obfuscating that call when prefs are updating. I'm fairly certain the plex framework itself is generating that log. Any suggestions?

**Comment by ukdtom** [comment] 2016-02-15 09:17
Changed WebTools
https://github.com/dagalufh/WebTools.bundle/commit/32d7d5e4bc629e536dbef016cd0f73fca580075d
Now supports Basic Auth header.
That way, it hopefully should be kept out of some parts of the log.
Above fix would go into V2.2 when released ;-)

When that's said, then yes, it's the framework that's doing it, so I raised this as a bug to Plex

**Comment by vanstinator** [comment] 2016-02-15 13:48
Hmmm. Not sure that covers this scenario as it looks like saving the Prefs on the actual Plex-created preferences screen is what is causing this. So yes it's a bug, but I don't think there's anything I can do about it.

**Comment by ukdtom** [comment] 2016-02-15 17:45
Correct, but still suggest, that you switch to basic header auth regardless

**Comment by vanstinator** [comment] 2016-02-15 17:46
I can do that.

**Closed as completed** 2016-02-15 17:47 UTC
Labels: bug

**Comment by ukdtom** [comment] 2016-02-15 18:53
Then remember, when testing this, to use my Tommy-Work branch, until V2.2 is released
